default_agent: test_agent
agents:
  test_agent:
    name: test_agent
    entrypoint: agents.py
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::206863353204:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-8bd92bdc12
      execution_role_auto_create: false
      account: '206863353204'
      region: us-west-2
      ecr_repository: 206863353204.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-test_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: test_agent-2aQI4YF3ua
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:206863353204:runtime/test_agent-2aQI4YF3ua
      agent_session_id: 1e27e431-1955-47e3-9122-584841a10576
    codebuild:
      project_name: bedrock-agentcore-test_agent-builder
      execution_role: arn:aws:iam::206863353204:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-8bd92bdc12
      source_bucket: bedrock-agentcore-codebuild-sources-206863353204-us-west-2
    memory:
      mode: STM_ONLY
      memory_id: test_agent_mem-AB5Sx3FVcO
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:206863353204:memory/test_agent_mem-AB5Sx3FVcO
      memory_name: test_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
