default_agent: test_agent
agents:
  test_agent:
    name: test_agent
    entrypoint: /Users/yusuke/github/agent-core-test/11_streaming/agents.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/yusuke/github/agent-core-test/11_streaming
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '206863353204'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: null
      memory_arn: null
      memory_name: test_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
